# INFRASTRUCTURE

DOWNLOAD_DELAY = 1.0
CONCURRENCY_PER_DOMAIN = 8
CAMOUFOX_CONCURRENCY_PER_DOMAIN = 1
PAGE_TIMEOUT_MS = 15000
DELAY_BEFORE_RETURN_HTML = 0.5
EMPTY_THRESHOLD_BYTES = 100
FALLBACK_FETCH_TIMEOUT_S = 15.0
