# INFRASTRUCTURE

OK        = "OK"
EMPTY     = "EMPTY"
RATE_SKIP = "RATE_SKIP"

TIMEOUT_WATCHDOG = "TIMEOUT_WATCHDOG"
TIMEOUT_NONCOOP  = "TIMEOUT_NONCOOP"
TIMEOUT_HTTPX    = "TIMEOUT_HTTPX"

ERROR_BROWSER = "ERROR_BROWSER"
ERROR_HTTP    = "ERROR_HTTP"
ERROR_PARSE   = "ERROR_PARSE"
ERROR_OTHER   = "ERROR_OTHER"
