# INFRASTRUCTURE

OK        = "OK"
EMPTY     = "EMPTY"
TIMEOUT   = "TIMEOUT"
ERROR     = "ERROR"
RATE_SKIP = "RATE_SKIP"

EMPTY_NO_RESULTS      = "EMPTY_NO_RESULTS"
EMPTY_NO_CONTAINER    = "EMPTY_NO_CONTAINER"
EMPTY_CONSENT         = "EMPTY_CONSENT"
EMPTY_BLOCK           = "EMPTY_BLOCK"
EMPTY_CONCURRENT_RACE = "EMPTY_CONCURRENT_RACE"

TIMEOUT_WATCHDOG = "TIMEOUT_WATCHDOG"
TIMEOUT_NONCOOP  = "TIMEOUT_NONCOOP"
TIMEOUT_HTTPX    = "TIMEOUT_HTTPX"

ERROR_BROWSER = "ERROR_BROWSER"
ERROR_HTTP    = "ERROR_HTTP"
ERROR_PARSE   = "ERROR_PARSE"
ERROR_OTHER   = "ERROR_OTHER"
